title: Khai Nguyen # your name (or website title) here
logo: "/images/khai.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data is beautiful  <br><br>
  <a href="https://www.linkedin.com/in/kh-ai/">View My LinkedIn Profile</a> 
   <br><br>
  
  <a href="https://github.com/Khaihuyennguyen">View My Github Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
